apiVersion: 1

datasources:
  - name: db
    uid: P26220D482FF390EF
    type: postgres
    url: "${POSTGRES_SERVER}:${POSTGRES_PORT}"
    user: "${POSTGRES_USER}"
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      database: "${POSTGRES_DB}"
      postgresVersion: 1300 # 1300 for PostgreSQL 13
      sslmode: 'disable'
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      connMaxLifetime: 14400